package defpackage;

/* JADX INFO: compiled from: r8-map-id-5f1ea74b072460be821fa7f2514cf36d220f69463b6062bff833a45851f543a6 */
/* JADX INFO: loaded from: classes.dex */
public final class fi1 {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    public final long I;
    public final long J;
    public final long K;
    public final long L;
    public final long M;
    public final long N;
    public final long O;
    public final long P;
    public final long Q;
    public final long R;
    public final long S;
    public final long T;
    public final long U;
    public final long V;
    public yy0 W;
    public yy0 X;
    public yy0 Y;
    public a51 Z;
    public final long a;
    public kra a0;
    public final long b;
    public lh2 b0;
    public final long c;
    public b65 c0;
    public final long d;
    public nr6 d0;
    public final long e;
    public pda e0;
    public final long f;
    public pda f0;
    public final long g;
    public xma g0;
    public final long h;
    public final long i;
    public final long j;
    public final long k;
    public final long l;
    public final long m;
    public final long n;
    public final long o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public fi1(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j10;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j20;
        this.u = j21;
        this.v = j22;
        this.w = j23;
        this.x = j24;
        this.y = j25;
        this.z = j26;
        this.A = j27;
        this.B = j28;
        this.C = j29;
        this.D = j30;
        this.E = j31;
        this.F = j32;
        this.G = j33;
        this.H = j34;
        this.I = j35;
        this.J = j36;
        this.K = j37;
        this.L = j38;
        this.M = j39;
        this.N = j40;
        this.O = j41;
        this.P = j42;
        this.Q = j43;
        this.R = j44;
        this.S = j45;
        this.T = j46;
        this.U = j47;
        this.V = j48;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("ColorScheme(primary=");
        a83.b(this.a, "onPrimary=", sb);
        a83.b(this.b, "primaryContainer=", sb);
        a83.b(this.c, "onPrimaryContainer=", sb);
        long j = this.d;
        a83.b(j, "inversePrimary=", sb);
        a83.b(this.e, "secondary=", sb);
        a83.b(this.f, "onSecondary=", sb);
        a83.b(this.g, "secondaryContainer=", sb);
        a83.b(this.h, "onSecondaryContainer=", sb);
        a83.b(this.i, "tertiary=", sb);
        a83.b(this.j, "onTertiary=", sb);
        a83.b(this.k, "tertiaryContainer=", sb);
        a83.b(this.l, "onTertiaryContainer=", sb);
        a83.b(this.m, "background=", sb);
        a83.b(this.n, "onBackground=", sb);
        a83.b(this.o, "surface=", sb);
        a83.b(this.p, "onSurface=", sb);
        a83.b(this.q, "surfaceVariant=", sb);
        a83.b(this.r, "onSurfaceVariant=", sb);
        a83.b(this.s, "surfaceTint=", sb);
        a83.b(this.t, "inverseSurface=", sb);
        a83.b(this.u, "inverseOnSurface=", sb);
        a83.b(this.v, "error=", sb);
        a83.b(this.w, "onError=", sb);
        a83.b(this.x, "errorContainer=", sb);
        a83.b(this.y, "onErrorContainer=", sb);
        a83.b(this.z, "outline=", sb);
        a83.b(this.A, "outlineVariant=", sb);
        a83.b(this.B, "scrim=", sb);
        a83.b(this.C, "surfaceBright=", sb);
        a83.b(this.D, "surfaceDim=", sb);
        a83.b(this.E, "surfaceContainer=", sb);
        a83.b(this.F, "surfaceContainerHigh=", sb);
        a83.b(this.G, "surfaceContainerHighest=", sb);
        a83.b(this.H, "surfaceContainerLow=", sb);
        a83.b(this.I, "surfaceContainerLowest=", sb);
        a83.b(this.J, "primaryFixed=", sb);
        a83.b(this.K, "primaryFixedDim=", sb);
        a83.b(this.L, "onPrimaryFixed=", sb);
        a83.b(j, "onPrimaryFixedVariant=", sb);
        a83.b(this.N, "secondaryFixed=", sb);
        a83.b(this.O, "secondaryFixedDim=", sb);
        a83.b(this.P, "onSecondaryFixed=", sb);
        a83.b(this.Q, "onSecondaryFixedVariant=", sb);
        a83.b(this.R, "tertiaryFixed=", sb);
        a83.b(this.S, "tertiaryFixedDim=", sb);
        a83.b(this.T, "onTertiaryFixed=", sb);
        a83.b(this.U, "onTertiaryFixedVariant=", sb);
        sb.append((Object) uh1.i(this.V));
        sb.append(')');
        return sb.toString();
    }
}
