package defpackage;

/* JADX INFO: compiled from: r8-map-id-5f1ea74b072460be821fa7f2514cf36d220f69463b6062bff833a45851f543a6 */
/* JADX INFO: loaded from: classes.dex */
public final class gza {
    public static final long A;
    public static final long A0;
    public static final jk4 A1;
    public static final long B;
    public static final ob4 B0;
    public static final long B1;
    public static final long C;
    public static final jk4 C0;
    public static final long C1;
    public static final ob4 D;
    public static final long D0;
    public static final long D1;
    public static final jk4 E;
    public static final long E0;
    public static final ob4 E1;
    public static final long F;
    public static final long F0;
    public static final jk4 F1;
    public static final long G;
    public static final ob4 G0;
    public static final long G1;
    public static final long H;
    public static final jk4 H0;
    public static final long H1;
    public static final ob4 I;
    public static final long I0;
    public static final long I1;
    public static final jk4 J;
    public static final long J0;
    public static final ob4 J1;
    public static final long K;
    public static final long K0;
    public static final jk4 K1;
    public static final long L;
    public static final ob4 L0;
    public static final long L1;
    public static final long M;
    public static final jk4 M0;
    public static final long M1;
    public static final ob4 N;
    public static final long N0;
    public static final long N1;
    public static final jk4 O;
    public static final long O0;
    public static final ob4 O1;
    public static final long P;
    public static final long P0;
    public static final jk4 P1;
    public static final long Q;
    public static final ob4 Q0;
    public static final long Q1;
    public static final long R;
    public static final jk4 R0;
    public static final long R1;
    public static final ob4 S;
    public static final long S0;
    public static final long S1;
    public static final jk4 T;
    public static final long T0;
    public static final ob4 T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final ob4 V0;
    public static final long W;
    public static final jk4 W0;
    public static final ob4 X;
    public static final long X0;
    public static final jk4 Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final jk4 a;
    public static final long a0;
    public static final ob4 a1;
    public static final long b;
    public static final long b0;
    public static final jk4 b1;
    public static final long c;
    public static final ob4 c0;
    public static final long c1;
    public static final long d;
    public static final jk4 d0;
    public static final long d1;
    public static final ob4 e;
    public static final long e0;
    public static final long e1;
    public static final jk4 f;
    public static final long f0;
    public static final ob4 f1;
    public static final long g;
    public static final long g0;
    public static final jk4 g1;
    public static final long h;
    public static final ob4 h0;
    public static final long h1;
    public static final long i;
    public static final jk4 i0;
    public static final long i1;
    public static final ob4 j;
    public static final long j0;
    public static final long j1;
    public static final jk4 k;
    public static final long k0;
    public static final ob4 k1;
    public static final long l;
    public static final long l0;
    public static final jk4 l1;
    public static final long m;
    public static final ob4 m0;
    public static final long m1;
    public static final long n;
    public static final jk4 n0;
    public static final long n1;
    public static final ob4 o;
    public static final long o0;
    public static final long o1;
    public static final jk4 p;
    public static final long p0;
    public static final ob4 p1;
    public static final long q;
    public static final long q0;
    public static final jk4 q1;
    public static final long r;
    public static final ob4 r0;
    public static final long r1;
    public static final long s;
    public static final jk4 s0;
    public static final long s1;
    public static final ob4 t;
    public static final long t0;
    public static final long t1;
    public static final jk4 u;
    public static final long u0;
    public static final ob4 u1;
    public static final long v;
    public static final long v0;
    public static final jk4 v1;
    public static final long w;
    public static final ob4 w0;
    public static final long w1;
    public static final long x;
    public static final jk4 x0;
    public static final long x1;
    public static final ob4 y;
    public static final long y0;
    public static final long y1;
    public static final jk4 z;
    public static final long z0;
    public static final ob4 z1;

    static {
        jk4 jk4Var = a0b.b;
        a = jk4Var;
        b = cka.a(24.0d);
        c = cka.b(16);
        d = cka.a(0.5d);
        ob4 ob4Var = a0b.e;
        e = ob4Var;
        f = jk4Var;
        g = cka.a(20.0d);
        h = cka.b(14);
        i = cka.a(0.2d);
        j = ob4Var;
        k = jk4Var;
        l = cka.a(16.0d);
        m = cka.b(12);
        n = cka.a(0.4d);
        o = ob4Var;
        jk4 jk4Var2 = a0b.a;
        p = jk4Var2;
        q = cka.a(64.0d);
        r = cka.b(57);
        long jA = cka.a(0.2d);
        dka[] dkaVarArr = bka.b;
        long j2 = jA & 1095216660480L;
        if (j2 == 0) {
            wc5.a("Cannot perform operation for Unspecified type.");
        }
        s = cka.c(-bka.c(jA), j2);
        t = ob4Var;
        u = jk4Var2;
        v = cka.a(52.0d);
        w = cka.b(45);
        x = cka.a(0.0d);
        y = ob4Var;
        z = jk4Var2;
        A = cka.a(44.0d);
        B = cka.b(36);
        C = cka.a(0.0d);
        D = ob4Var;
        E = jk4Var2;
        F = cka.a(40.0d);
        G = cka.b(32);
        H = cka.a(0.0d);
        I = ob4Var;
        J = jk4Var2;
        K = cka.a(36.0d);
        L = cka.b(28);
        M = cka.a(0.0d);
        N = ob4Var;
        O = jk4Var2;
        P = cka.a(32.0d);
        Q = cka.b(24);
        R = cka.a(0.0d);
        S = ob4Var;
        T = jk4Var;
        U = cka.a(20.0d);
        V = cka.b(14);
        W = cka.a(0.1d);
        ob4 ob4Var2 = a0b.d;
        X = ob4Var2;
        Y = jk4Var;
        Z = cka.a(16.0d);
        a0 = cka.b(12);
        b0 = cka.a(0.5d);
        c0 = ob4Var2;
        d0 = jk4Var;
        e0 = cka.a(16.0d);
        f0 = cka.b(11);
        g0 = cka.a(0.5d);
        h0 = ob4Var2;
        i0 = jk4Var2;
        j0 = cka.a(28.0d);
        k0 = cka.b(22);
        l0 = cka.a(0.0d);
        m0 = ob4Var;
        n0 = jk4Var;
        o0 = cka.a(24.0d);
        p0 = cka.b(16);
        q0 = cka.a(0.2d);
        r0 = ob4Var2;
        s0 = jk4Var;
        t0 = cka.a(20.0d);
        u0 = cka.b(14);
        v0 = cka.a(0.1d);
        w0 = ob4Var2;
        x0 = jk4Var;
        y0 = cka.a(24.0d);
        z0 = cka.b(16);
        A0 = cka.a(0.15d);
        B0 = ob4Var2;
        C0 = jk4Var;
        D0 = cka.a(20.0d);
        E0 = cka.b(14);
        F0 = cka.a(0.25d);
        G0 = ob4Var2;
        H0 = jk4Var;
        I0 = cka.a(16.0d);
        J0 = cka.b(12);
        K0 = cka.a(0.4d);
        L0 = ob4Var2;
        M0 = jk4Var2;
        N0 = cka.a(64.0d);
        O0 = cka.b(57);
        P0 = cka.b(0);
        Q0 = ob4Var2;
        R0 = jk4Var2;
        S0 = cka.a(52.0d);
        T0 = cka.b(45);
        U0 = cka.b(0);
        V0 = ob4Var2;
        W0 = jk4Var2;
        X0 = cka.a(44.0d);
        Y0 = cka.b(36);
        Z0 = cka.b(0);
        a1 = ob4Var2;
        b1 = jk4Var2;
        c1 = cka.a(40.0d);
        d1 = cka.b(32);
        e1 = cka.b(0);
        f1 = ob4Var2;
        g1 = jk4Var2;
        h1 = cka.a(36.0d);
        i1 = cka.b(28);
        j1 = cka.b(0);
        k1 = ob4Var2;
        l1 = jk4Var2;
        m1 = cka.a(32.0d);
        n1 = cka.b(24);
        o1 = cka.b(0);
        p1 = ob4Var2;
        q1 = jk4Var;
        r1 = cka.a(20.0d);
        s1 = cka.b(14);
        t1 = cka.a(0.1d);
        ob4 ob4Var3 = a0b.c;
        u1 = ob4Var3;
        v1 = jk4Var;
        w1 = cka.a(16.0d);
        x1 = cka.b(12);
        y1 = cka.a(0.5d);
        z1 = ob4Var3;
        A1 = jk4Var;
        B1 = cka.a(16.0d);
        C1 = cka.b(11);
        D1 = cka.a(0.5d);
        E1 = ob4Var3;
        F1 = jk4Var2;
        G1 = cka.a(28.0d);
        H1 = cka.b(22);
        I1 = cka.b(0);
        J1 = ob4Var2;
        K1 = jk4Var;
        L1 = cka.a(24.0d);
        M1 = cka.b(16);
        N1 = cka.a(0.15d);
        O1 = ob4Var3;
        P1 = jk4Var;
        Q1 = cka.a(20.0d);
        R1 = cka.b(14);
        S1 = cka.a(0.1d);
        T1 = ob4Var3;
    }
}
