package defpackage;

import com.hwpo_training_app.R;

/* JADX INFO: loaded from: classes.dex */
public final class lh8 {
    public static final int[] a = {R.attr.frameAspectRatio, R.attr.resize_mode};
    public static final int[] b = {R.attr.ad_marker_color, R.attr.ad_marker_width, R.attr.bar_gravity, R.attr.bar_height, R.attr.buffered_color, R.attr.played_ad_marker_color, R.attr.played_color, R.attr.scrubber_color, R.attr.scrubber_disabled_size, R.attr.scrubber_dragged_size, R.attr.scrubber_drawable, R.attr.scrubber_enabled_size, R.attr.touch_target_height, R.attr.unplayed_color};
    public static final int[] c = {R.attr.ad_marker_color, R.attr.ad_marker_width, R.attr.animation_enabled, R.attr.bar_gravity, R.attr.bar_height, R.attr.buffered_color, R.attr.controller_layout_id, R.attr.fastforward_icon, R.attr.fullscreen_enter_icon, R.attr.fullscreen_exit_icon, R.attr.next_icon, R.attr.pause_icon, R.attr.play_icon, R.attr.played_ad_marker_color, R.attr.played_color, R.attr.previous_icon, R.attr.repeat_all_icon, R.attr.repeat_off_icon, R.attr.repeat_one_icon, R.attr.repeat_toggle_modes, R.attr.rewind_icon, R.attr.scrubber_color, R.attr.scrubber_disabled_size, R.attr.scrubber_dragged_size, R.attr.scrubber_drawable, R.attr.scrubber_enabled_size, R.attr.show_fastforward_button, R.attr.show_next_button, R.attr.show_previous_button, R.attr.show_rewind_button, R.attr.show_shuffle_button, R.attr.show_subtitle_button, R.attr.show_timeout, R.attr.show_vr_button, R.attr.shuffle_off_icon, R.attr.shuffle_on_icon, R.attr.subtitle_off_icon, R.attr.subtitle_on_icon, R.attr.time_bar_min_update_interval, R.attr.time_bar_scrubbing_enabled, R.attr.touch_target_height, R.attr.unplayed_color, R.attr.vr_icon};
    public static final int[] d = {R.attr.ad_marker_color, R.attr.ad_marker_width, R.attr.animation_enabled, R.attr.artwork_display_mode, R.attr.auto_show, R.attr.bar_gravity, R.attr.bar_height, R.attr.buffered_color, R.attr.controller_layout_id, R.attr.default_artwork, R.attr.fastforward_icon, R.attr.fullscreen_enter_icon, R.attr.fullscreen_exit_icon, R.attr.hide_during_ads, R.attr.hide_on_touch, R.attr.image_display_mode, R.attr.keep_content_on_player_reset, R.attr.next_icon, R.attr.pause_icon, R.attr.play_icon, R.attr.played_ad_marker_color, R.attr.played_color, R.attr.player_layout_id, R.attr.previous_icon, R.attr.repeat_all_icon, R.attr.repeat_off_icon, R.attr.repeat_one_icon, R.attr.repeat_toggle_modes, R.attr.resize_mode, R.attr.rewind_icon, R.attr.scrubber_color, R.attr.scrubber_disabled_size, R.attr.scrubber_dragged_size, R.attr.scrubber_drawable, R.attr.scrubber_enabled_size, R.attr.show_buffering, R.attr.show_shuffle_button, R.attr.show_subtitle_button, R.attr.show_timeout, R.attr.show_vr_button, R.attr.shuffle_off_icon, R.attr.shuffle_on_icon, R.attr.shutter_background_color, R.attr.subtitle_off_icon, R.attr.subtitle_on_icon, R.attr.surface_type, R.attr.time_bar_min_update_interval, R.attr.time_bar_scrubbing_enabled, R.attr.touch_target_height, R.attr.unplayed_color, R.attr.use_artwork, R.attr.use_controller, R.attr.vr_icon};
}
