package defpackage;

import com.intercom.twig.BuildConfig;
import io.intercom.android.sdk.m5.conversation.utils.audio.AudioConstants;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;

/* JADX INFO: compiled from: r8-map-id-5f1ea74b072460be821fa7f2514cf36d220f69463b6062bff833a45851f543a6 */
/* JADX INFO: loaded from: classes.dex */
public final class wfc {
    public static final ufc A;
    public static final ufc A0;
    public static final ufc B;
    public static final ufc B0;
    public static final ufc C;
    public static final ufc C0;
    public static final ufc D;
    public static final ufc D0;
    public static final ufc E;
    public static final ufc E0;
    public static final ufc F;
    public static final ufc F0;
    public static final ufc G;
    public static final ufc G0;
    public static final ufc H;
    public static final ufc H0;
    public static final ufc I;
    public static final ufc I0;
    public static final ufc J;
    public static final ufc J0;
    public static final ufc K;
    public static final ufc K0;
    public static final ufc L;
    public static final ufc L0;
    public static final ufc M;
    public static final ufc M0;
    public static final ufc N;
    public static final ufc N0;
    public static final ufc O;
    public static final ufc O0;
    public static final ufc P;
    public static final ufc P0;
    public static final ufc Q;
    public static final ufc Q0;
    public static final ufc R;
    public static final ufc R0;
    public static final ufc S;
    public static final ufc S0;
    public static final ufc T;
    public static final ufc T0;
    public static final ufc U;
    public static final ufc U0;
    public static final ufc V;
    public static final ufc V0;
    public static final ufc W;
    public static final ufc W0;
    public static final ufc X;
    public static final ufc X0;
    public static final ufc Y;
    public static final ufc Y0;
    public static final ufc Z;
    public static final ufc Z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final ufc a0;
    public static final ufc a1;
    public static final ufc b;
    public static final ufc b0;
    public static final ufc b1;
    public static final ufc c;
    public static final ufc c0;
    public static final ufc c1;
    public static final ufc d;
    public static final ufc d0;
    public static final ufc d1;
    public static final ufc e;
    public static final ufc e0;
    public static final ufc e1;
    public static final ufc f;
    public static final ufc f0;
    public static final ufc f1;
    public static final ufc g;
    public static final ufc g0;
    public static final ufc g1;
    public static final ufc h;
    public static final ufc h0;
    public static final ufc h1;
    public static final ufc i;
    public static final ufc i0;
    public static final ufc i1;
    public static final ufc j;
    public static final ufc j0;
    public static final ufc j1;
    public static final ufc k;
    public static final ufc k0;
    public static final ufc l;
    public static final ufc l0;
    public static final ufc m;
    public static final ufc m0;
    public static final ufc n;
    public static final ufc n0;
    public static final ufc o;
    public static final ufc o0;
    public static final ufc p;
    public static final ufc p0;
    public static final ufc q;
    public static final ufc q0;
    public static final ufc r;
    public static final ufc r0;
    public static final ufc s;
    public static final ufc s0;
    public static final ufc t;
    public static final ufc t0;
    public static final ufc u;
    public static final ufc u0;
    public static final ufc v;
    public static final ufc v0;
    public static final ufc w;
    public static final ufc w0;
    public static final ufc x;
    public static final ufc x0;
    public static final ufc y;
    public static final ufc y0;
    public static final ufc z;
    public static final ufc z0;

    static {
        Collections.synchronizedSet(new HashSet());
        b = a("measurement.ad_id_cache_time", 10000L, ay.t, false);
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, p50.t, false);
        d = a("measurement.monitoring.sample_period_millis", 86400000L, wx5.t, false);
        e = a("measurement.config.cache_time", 86400000L, l58.u, false);
        f = a("measurement.config.url_scheme", "https", x17.t, false);
        g = a("measurement.config.url_authority", "app-measurement.com", s7.u, false);
        h = a("measurement.upload.max_bundles", 100, p84.t, false);
        i = a("measurement.upload.max_batch_size", 65536, sz9.u, false);
        j = a("measurement.upload.max_bundle_size", 65536, oj5.t, false);
        k = a("measurement.upload.max_events_per_bundle", 1000, us3.v, false);
        l = a("measurement.upload.max_events_per_day", 100000, zx.t, false);
        m = a("measurement.upload.max_error_events_per_day", 1000, md6.v, false);
        n = a("measurement.upload.max_public_events_per_day", 50000, ws0.t, false);
        o = a("measurement.upload.max_conversions_per_day", 10000, zd6.B, false);
        p = a("measurement.upload.max_realtime_events_per_day", 10, rc5.t, false);
        q = a("measurement.store.max_stored_events_per_app", 100000, zc5.t, false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", gj7.v, false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", q69.u, false);
        t = a("measurement.sgtm.service_upload_apps_list", BuildConfig.FLAVOR, hl3.u, false);
        u = a("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", i03.F, false);
        v = a("measurement.sgtm.upload.retry_interval", 600000L, kl3.t, false);
        w = a("measurement.sgtm.upload.retry_max_wait", 21600000L, ol3.t, false);
        x = a("measurement.sgtm.batch.retry_interval", 1800000L, zs4.w, false);
        y = a("measurement.sgtm.batch.retry_max_wait", 21600000L, p48.u, false);
        z = a("measurement.sgtm.batch.retry_max_count", 10, lo.u, false);
        A = a("measurement.sgtm.upload.max_queued_batches", 5000, z69.u, false);
        B = a("measurement.sgtm.upload.batches_retrieval_limit", 5, by5.t, false);
        C = a("measurement.sgtm.upload.min_delay_after_startup", 5000L, y48.Y, false);
        D = a("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, pt9.J, false);
        E = a("measurement.sgtm.upload.min_delay_after_background", 600000L, su0.u, false);
        F = a("measurement.sgtm.batch.long_queuing_threshold", 14400000L, vca.u, false);
        G = a("measurement.upload.backoff_period", 43200000L, e23.t, false);
        a("measurement.upload.window_interval", 3600000L, sm3.w, false);
        H = a("measurement.upload.interval", 3600000L, uy5.u, false);
        I = a("measurement.upload.realtime_upload_interval", 10000L, lp.t, false);
        J = a("measurement.upload.debug_upload_interval", 1000L, pu9.t, false);
        K = a("measurement.upload.minimum_delay", 500L, su4.t, false);
        L = a("measurement.alarm_manager.minimum_interval", 60000L, fn3.u, false);
        M = a("measurement.upload.stale_data_deletion_interval", 86400000L, m33.u, false);
        N = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, bl7.t, false);
        O = a("measurement.upload.initial_upload_delay_time", 15000L, lv9.u, false);
        P = a("measurement.upload.retry_time", 1800000L, ov9.u, false);
        Q = a("measurement.upload.retry_count", 6, xl7.v, false);
        R = a("measurement.upload.max_queue_time", 518400000L, yl7.w, false);
        S = a("measurement.upload.google_signal_max_queue_time", Long.valueOf(AudioConstants.MAX_RECORDING_DURATION_MS), dx0.v, false);
        T = a("measurement.lifetimevalue.max_currency_tracked", 4, b78.t, false);
        U = a("measurement.audience.filter_result_max_count", 200, i90.t, false);
        V = a("measurement.upload.max_public_user_properties", 100, null, false);
        W = a("measurement.upload.max_event_name_cardinality", 2000, null, false);
        X = a("measurement.upload.max_public_event_params", 100, null, false);
        Y = a("measurement.service_client.idle_disconnect_millis", 5000L, b64.u, false);
        Z = a("measurement.service_client.reconnect_millis", 1000L, rcc.t, false);
        Boolean bool = Boolean.FALSE;
        a0 = a("measurement.test.test_boolean_flag", bool, lk6.t, false);
        b0 = a("measurement.test.test_string_flag", "---", bsc.x, false);
        c0 = a("measurement.test.test_long_flag", -1L, b47.u, false);
        a("measurement.test.test_cached_long_flag", -1L, d47.t, true);
        d0 = a("measurement.test.test_int_flag", -2, vk6.t, false);
        e0 = a("measurement.test.test_double_flag", Double.valueOf(-3.0d), ym7.X, false);
        a("measurement.experiment.max_ids", 50, z63.t, false);
        f0 = a("measurement.upload.max_item_scoped_custom_parameters", 27, wcc.t, false);
        g0 = a("measurement.upload.max_event_parameter_value_length", 500, zb9.w, true);
        h0 = a("measurement.max_bundles_per_iteration", 100, zcc.t, false);
        i0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, oy0.u, false);
        j0 = a("measurement.redaction.app_instance_id.ttl", 7200000L, e9.t, false);
        k0 = a("measurement.rb.attribution.client.min_ad_services_version", 7, xs.x, false);
        l0 = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, kz0.w, false);
        m0 = a("measurement.rb.attribution.uri_scheme", "https", eo7.t, false);
        n0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", tdc.t, false);
        o0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", lp1.u, false);
        p0 = a("measurement.session.engagement_interval", 3600000L, un2.t, false);
        q0 = a("measurement.rb.attribution.app_allowlist", BuildConfig.FLAVOR, wdc.t, false);
        r0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", xdc.t, false);
        s0 = a("measurement.rb.attribution.event_params", "value|currency", oua.u, false);
        t0 = a("measurement.rb.attribution.query_parameters_to_remove", BuildConfig.FLAVOR, pua.u, false);
        u0 = a("measurement.rb.attribution.max_queue_time", 864000000L, sb4.t, false);
        v0 = a("measurement.rb.attribution.max_retry_delay_seconds", 16, ydc.t, false);
        w0 = a("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, b0a.E, false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, cdb.t, false);
        x0 = a("measurement.rb.max_trigger_registrations_per_day", 1000, oq3.t, false);
        Boolean bool2 = Boolean.TRUE;
        y0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, ja8.v, false);
        z0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, nha.t, false);
        A0 = a("measurement.rb.attribution.notify_app_delay_millis", 3000, f31.x, false);
        a("measurement.config.default_flag_values", bool2, dc4.u, false);
        B0 = a("measurement.upload.diagnostic_upload_interval", 3600000L, zv.t, false);
        C0 = a("measurement.quality.checksum", bool, null, false);
        D0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, gec.t, false);
        E0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, rh0.t, false);
        F0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, th0.t, true);
        G0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, gi0.t, false);
        H0 = a("measurement.integration.disable_firebase_instance_id", bool, f41.w, false);
        I0 = a("measurement.collection.service.update_with_analytics_fix", bool, g41.u, false);
        J0 = a("measurement.service.storage_consent_support_version", 203600, aj0.A, false);
        K0 = a("measurement.service.store_null_safelist", bool2, sd.u, false);
        L0 = a("measurement.service.store_safelist", bool2, td.u, false);
        M0 = a("measurement.session_stitching_token_enabled", bool, ml5.B, false);
        N0 = a("measurement.sgtm.client.upload_on_backgrounded.dev", bool, dfc.t, true);
        O0 = a("measurement.rb.attribution.service", bool2, ws3.y, true);
        P0 = a("measurement.rb.attribution.client2", bool2, d3a.w, true);
        Q0 = a("measurement.rb.attribution.uuid_generation", bool2, kt7.v, false);
        R0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, nt3.v, false);
        S0 = a("measurement.client.sessions.enable_fix_background_engagement", bool2, zu1.u, false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, vx.u, false);
        a("measurement.remove_conflicting_first_party_apis.dev", bool, wx.t, false);
        T0 = a("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, xx.t, false);
        U0 = a("measurement.experiment.enable_phenotype_experiment_reporting", bool2, ve.v, false);
        V0 = a("measurement.experiment.enable_passthrough_experiment_reporting", bool2, we.v, false);
        W0 = a("measurement.set_default_event_parameters.fix_service_request_ordering", bool, iw5.t, false);
        X0 = a("measurement.set_default_event_parameters.fix_app_update_logging", bool2, t2.u, false);
        Y0 = a("measurement.service.fix_stop_bundling_bug", bool2, hac.t, false);
        Z0 = a("measurement.gbraid_campaign.stop_lgclid", bool, ha7.v, false);
        a1 = a("measurement.gbraid_campaign.deep_link_url", bool, hu1.x, false);
        b1 = a("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", mm8.t, false);
        c1 = a("measurement.edpb.service", bool, zg1.t, false);
        d1 = a("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", lac.t, false);
        e1 = a("measurement.robust_time_source_2", bool, od3.t, false);
        f1 = a("measurement.manual_iap_logging.client_service", bool, rhb.u, false);
        g1 = a("measurement.dsid_consent_only.app_allowlist1", BuildConfig.FLAVOR, ww5.u, false);
        h1 = a("measurement.dsid_consent_only.app_allowlist2", BuildConfig.FLAVOR, ym.t, false);
        i1 = a("measurement.dsid_consent_only.app_allowlist3", BuildConfig.FLAVOR, mh1.u, false);
        j1 = a("measurement.diagnostics.enabled", bool, wx2.u, false);
    }

    public static ufc a(String str, Object obj, jac jacVar, boolean z2) {
        ufc ufcVar = new ufc(str, obj, jacVar);
        if (z2) {
            a.add(ufcVar);
        }
        return ufcVar;
    }
}
