package defpackage;

/* JADX INFO: compiled from: r8-map-id-5f1ea74b072460be821fa7f2514cf36d220f69463b6062bff833a45851f543a6 */
/* JADX INFO: loaded from: classes.dex */
public final class yh1 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = ms7.w;
        a = j2;
        b = ms7.e;
        c = ms7.f;
        d = ms7.u;
        long j3 = ms7.G;
        e = j3;
        f = ms7.l;
        long j4 = ms7.h;
        g = j4;
        h = ms7.b;
        i = ms7.a;
        j = ms7.D;
        long j5 = ms7.C;
        k = j5;
        l = j5;
        m = ms7.E;
        n = ms7.J;
        long j6 = ms7.I;
        o = j6;
        p = j6;
        q = ms7.L;
        r = j4;
        s = ms7.x;
        t = ms7.Q;
        long j7 = ms7.P;
        u = j7;
        v = j7;
        w = ms7.S;
        x = ms7.y;
        y = ms7.A;
        z = ms7.F;
        long j8 = ms7.H;
        A = j8;
        B = j8;
        C = j3;
        D = ms7.g;
        E = ms7.M;
        long j9 = ms7.O;
        F = j9;
        G = j9;
        H = ms7.N;
        I = j2;
        J = j2;
        K = ms7.t;
        L = ms7.s;
        M = ms7.r;
        N = ms7.v;
        O = ms7.i;
        P = ms7.q;
        Q = ms7.B;
        R = ms7.T;
        long j10 = ms7.V;
        S = j10;
        T = j10;
        U = ms7.U;
    }
}
