// ==UserScript==
// @name         Canvas + Gradescope Student Deadline Extensions
// @namespace    https://gatech.instructure.com/
// @version      1.10.0
// @description  Adds a course-level tool for Canvas student deadline overrides and matched Gradescope extensions.
// @author       Ronnie Howard
// @match        https://gatech.instructure.com/courses/*
// @run-at       document-idle
// @grant        GM_xmlhttpRequest
// @grant        GM_getValue
// @grant        GM_setValue
// @connect      gradescope.com
// @connect      www.gradescope.com
// ==/UserScript==

(function () {
  'use strict';

  const GS_BASE = 'https://www.gradescope.com';
  const courseId = location.pathname.match(/^\/courses\/(\d+)/)?.[1];
  if (!courseId) return;

  const HISTORY_KEY='cgde-history-v1';
  const TIME_SETTINGS_KEY='cgde-default-times-v1';
  const state = { course:null, students:[], assignments:[], student:null, selectedStudentIds:new Set(), selectedAssignments:new Set(), current:new Map(), gs:null, gsCsrf:'', plans:[], skipped:[], stopRequested:false };
  const css = `
    :root{--cgde-blue:#075a9c;--cgde-blue-dark:#064a80;--cgde-gold:#b3a369;--cgde-ink:#273642;--cgde-muted:#667681;--cgde-line:#d8dee3;--cgde-soft:#f5f7f8;--cgde-focus:#1683c6;--cgde-green:#137333;--cgde-red:#b3261e;--cgde-amber:#8a4b08}
    .cgde-launch{position:fixed;right:26px;bottom:24px;z-index:9997;display:inline-flex;align-items:center;gap:8px;min-height:44px;padding:0 17px;border:1px solid #fff4;border-radius:8px;background:var(--cgde-blue);color:#fff;font-weight:700;letter-spacing:.01em;box-shadow:0 6px 20px #1d2b3640;cursor:pointer;transition:transform .15s,box-shadow .15s,background .15s}.cgde-launch::before{content:'◷';font-size:19px}.cgde-launch:hover{background:var(--cgde-blue-dark);box-shadow:0 8px 24px #1d2b3650;transform:translateY(-1px)}
    .cgde-backdrop{position:fixed;inset:0;z-index:10000;display:flex;align-items:center;justify-content:center;padding:24px;background:#17232c99;backdrop-filter:blur(3px)}.cgde-hidden{display:none!important}
    .cgde-modal{display:flex;flex-direction:column;width:min(1180px,96vw);max-height:92vh;overflow:hidden;border:1px solid #ffffff70;border-radius:14px;background:#fff;color:var(--cgde-ink);box-shadow:0 24px 70px #10182070}
    .cgde-header{position:relative;display:flex;align-items:center;gap:14px;padding:20px 24px 18px;border-bottom:1px solid var(--cgde-line);background:linear-gradient(135deg,#fff 0%,#f6f9fb 100%)}.cgde-header::before{content:'';position:absolute;inset:0 auto 0 0;width:5px;background:var(--cgde-gold)}.cgde-title-wrap{flex:1}.cgde-eyebrow{margin:0 0 2px;color:var(--cgde-blue);font-size:11px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.cgde-header h2{margin:0;font-size:23px;line-height:1.25}.cgde-subtitle{margin:3px 0 0;color:var(--cgde-muted);font-size:13px}.cgde-close{display:grid;place-items:center;width:38px;height:38px;border:0;border-radius:50%;background:transparent;color:#52616c;font-size:27px;line-height:1;cursor:pointer}.cgde-close:hover{background:#e9eef1;color:var(--cgde-ink)}
    .cgde-body{overflow:auto;padding:20px 24px 26px;background:#fbfcfc}.cgde-grid{display:grid;grid-template-columns:minmax(300px,.9fr) minmax(520px,1.7fr);gap:16px;margin-bottom:16px}.cgde-card{padding:17px 18px;border:1px solid var(--cgde-line);border-radius:10px;background:#fff;box-shadow:0 1px 2px #192a3510}.cgde-card h3{display:flex;align-items:center;gap:8px;margin:0 0 13px;font-size:16px}.cgde-card h3::before{display:grid;place-items:center;width:25px;height:25px;border-radius:50%;background:#e7f1f8;color:var(--cgde-blue);font-size:12px;font-weight:800}.cgde-grid .cgde-card:first-child h3::before{content:'1'}.cgde-grid .cgde-card:nth-child(2) h3::before{content:'2'}.cgde-assignment-search h3::before{content:'3'}
    .cgde-field{display:flex;flex-direction:column;gap:5px;margin-bottom:10px}.cgde-field>span{color:#495862;font-size:12px;font-weight:700}.cgde-input,.cgde-select{height:42px;min-height:42px;box-sizing:border-box;margin:0!important;padding:7px 10px!important;border:1px solid #9ba7af!important;border-radius:6px!important;background:#fff!important;color:var(--cgde-ink)!important;font-size:14px!important;line-height:1.35!important;transition:border .15s,box-shadow .15s}.cgde-input:focus,.cgde-select:focus{border-color:var(--cgde-focus)!important;box-shadow:0 0 0 3px #1683c620!important;outline:0}.cgde-select{width:100%}.cgde-input[type=date]{min-width:164px;padding:7px 9px!important;color-scheme:light}.cgde-input[type=date]::-webkit-datetime-edit{display:flex;align-items:center;min-height:24px;padding:0}.cgde-input[type=date]::-webkit-date-and-time-value{min-height:24px;text-align:left}
    .cgde-modes{display:flex;flex-wrap:wrap;align-items:end;gap:11px 14px}.cgde-inline{display:flex;align-items:center;gap:6px;min-height:36px}.cgde-inline input[type=radio],.cgde-inline input[type=checkbox]{accent-color:var(--cgde-blue)}.cgde-inline input[type=number]{width:76px}.cgde-date{width:184px}.cgde-modes #cgde-find-repairs{margin-left:auto}.cgde-repair-banner{display:flex;align-items:center;gap:10px;flex-basis:100%;margin-top:3px;padding:10px 12px;border:1px solid #b8d7ea;border-radius:7px;background:#edf7fc;color:#155577}.cgde-repair-banner strong{margin-right:auto}.cgde-repair-banner .cgde-button{min-height:30px;padding:4px 9px;background:#fff}
    .cgde-search-results{position:relative;z-index:2;max-height:205px;overflow:auto;margin-top:5px;border:1px solid var(--cgde-line);border-radius:8px;background:#fff;box-shadow:0 7px 20px #1b2d3820}.cgde-search-result{display:flex;align-items:center;width:100%;padding:10px 12px;border:0;border-bottom:1px solid #e8ecef;background:#fff;color:var(--cgde-ink);text-align:left;cursor:pointer}.cgde-search-result::after{content:'+ Add';margin-left:auto;padding-left:12px;color:var(--cgde-blue);font-size:12px;font-weight:800}.cgde-search-result:last-child{border-bottom:0}.cgde-search-result:hover,.cgde-search-result:focus{background:#edf6fc;outline:0}.cgde-search-result strong{display:block}.cgde-search-result small{display:block;margin-top:2px;color:var(--cgde-muted)}.cgde-selected-person{padding:9px 11px;border:1px solid #b9dec5;border-radius:6px;background:#edf8f0;color:var(--cgde-green);font-weight:650}.cgde-assignment-search{margin-bottom:16px}.cgde-assignment-toolbar{display:flex;align-items:end;gap:14px}.cgde-assignment-toolbar .cgde-field{flex:1;margin:0}.cgde-queue-heading{display:flex;align-items:center;justify-content:space-between;margin:18px 2px 8px}.cgde-queue-heading h3{margin:0;font-size:17px}.cgde-remove{padding:5px 7px;border:0;border-radius:5px;background:transparent;color:var(--cgde-red);font-size:12px;font-weight:700;cursor:pointer}.cgde-remove:hover{background:#fff0ef}.cgde-empty-search{padding:12px;color:var(--cgde-muted)}
    #cgde-student-results .cgde-search-result::after{content:'Select'}
    .cgde-student-chips{display:flex;flex-wrap:wrap;gap:6px;min-height:36px}.cgde-student-chip{display:inline-flex;align-items:center;gap:7px;padding:7px 8px 7px 10px;border:1px solid #b9dec5;border-radius:999px;background:#edf8f0;color:var(--cgde-green);font-size:12px;font-weight:700}.cgde-student-chip button{display:grid;place-items:center;width:20px;height:20px;padding:0;border:0;border-radius:50%;background:#d7eddd;color:#215d32;line-height:1;cursor:pointer}.cgde-student-chip button:hover{background:#c4e4cd}.cgde-student-empty{padding:8px 0;color:var(--cgde-muted);font-size:12px}
    .cgde-table-wrap{overflow:auto;border:1px solid var(--cgde-line);border-radius:9px;background:#fff;box-shadow:0 1px 2px #192a3510}.cgde-table{width:100%;min-width:1160px;border-collapse:separate;border-spacing:0;font-size:12px}.cgde-table th{position:sticky;top:0;z-index:1;padding:10px 9px;border-bottom:1px solid var(--cgde-line);background:#f0f3f5;color:#4c5b65;text-align:left;font-size:11px;letter-spacing:.025em;white-space:nowrap}.cgde-table td{padding:11px 9px;border-top:1px solid #edf0f2;vertical-align:middle}.cgde-table tbody tr:first-child td{border-top:0}.cgde-table tr:hover td{background:#fafcfd}.cgde-table .cgde-name{min-width:210px;font-size:13px;font-weight:700}.cgde-table .cgde-name small{display:block;margin-top:3px;color:var(--cgde-muted);font-size:11px;font-weight:400}.cgde-table input[type=date]{display:block;width:158px!important;height:42px!important;min-height:42px!important;box-sizing:border-box!important;margin:0!important;padding:7px 8px!important;border:1px solid #aab4ba!important;border-radius:6px!important;background:#fff!important;color:var(--cgde-ink)!important;font-size:13px!important;line-height:1.35!important;color-scheme:light}.cgde-table input[type=date]::-webkit-datetime-edit{display:flex;align-items:center;min-height:24px;padding:0}.cgde-table input[type=date]::-webkit-date-and-time-value{min-height:24px;text-align:left}.cgde-system-date{min-width:142px}.cgde-system-date span{display:block;white-space:nowrap}.cgde-system-date small{display:block;margin-top:3px;color:var(--cgde-muted);font-size:10px}.cgde-muted{color:var(--cgde-muted)}.cgde-ok{color:var(--cgde-green)}.cgde-warn{color:var(--cgde-amber)}.cgde-error{color:var(--cgde-red)}
    .cgde-map-select{display:block;width:205px!important;height:30px!important;min-height:30px!important;margin-top:6px!important;padding:3px 24px 3px 6px!important;border:1px solid #bdc6cc!important;border-radius:5px!important;background:#fff!important;color:#52616c!important;font-size:10px!important;font-weight:400!important}
    .cgde-footer{display:flex;align-items:center;gap:10px;padding:14px 24px;border-top:1px solid var(--cgde-line);background:#fff}.cgde-status{flex:1;min-width:0;color:#52616c;font-size:13px}.cgde-button{min-height:38px;padding:7px 13px;border:1px solid #96a2aa;border-radius:6px;background:#fff;color:var(--cgde-ink);font-weight:700;cursor:pointer;transition:background .12s,border .12s,transform .12s}.cgde-button:hover:not(:disabled){border-color:#687984;background:#f1f4f5}.cgde-button:active:not(:disabled){transform:translateY(1px)}.cgde-primary{border-color:var(--cgde-blue);background:var(--cgde-blue);color:#fff}.cgde-primary:hover:not(:disabled){border-color:var(--cgde-blue-dark);background:var(--cgde-blue-dark)}.cgde-button:disabled{opacity:.46;cursor:not-allowed}
    .cgde-summary{margin:0 24px 16px;padding:15px 17px;border:1px solid var(--cgde-line);border-radius:9px;background:#fff}.cgde-summary-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.cgde-summary h3{margin:0}.cgde-summary h4{margin:13px 0 4px}.cgde-summary ul{margin:5px 0;padding-left:22px}.cgde-summary li{margin:4px 0}.cgde-summary-note{margin:3px 0 0;color:var(--cgde-muted);font-size:12px}.cgde-summary-errors{margin-top:10px;padding:9px 11px;border-radius:6px;background:#fff0ef}
    .cgde-history{margin-top:16px;border:1px solid var(--cgde-line);border-radius:9px;background:#fff}.cgde-history>summary{padding:11px 14px;color:#45545e;font-weight:700;cursor:pointer}.cgde-history[open]>summary{border-bottom:1px solid var(--cgde-line);background:var(--cgde-soft)}.cgde-history-body{max-height:300px;overflow:auto;padding:5px 14px}.cgde-history-run{padding:11px 0;border-bottom:1px solid #e8ecef}.cgde-history-run:last-child{border-bottom:0}.cgde-history-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.cgde-history-items{margin:6px 0 0;padding-left:20px;font-size:12px}
    @media(max-width:820px){.cgde-grid{grid-template-columns:1fr}.cgde-launch{right:12px;bottom:12px}.cgde-backdrop{padding:6px}.cgde-modal{max-height:98vh;border-radius:9px}.cgde-body{padding:14px}.cgde-header,.cgde-footer{padding-left:16px;padding-right:16px}.cgde-assignment-toolbar{align-items:stretch;flex-direction:column}.cgde-modes #cgde-find-repairs{margin-left:0}}
  `;

  function el(tag, className='', text='') { const node=document.createElement(tag); node.className=className; if(text) node.textContent=text; return node; }
  function normalize(value) { return String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim(); }
  function escapeHtml(value) { return String(value??'').replace(/[&<>"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); }
  function formatLocal(value) { if(!value) return ''; const d=new Date(value); const local=new Date(d.getTime()-d.getTimezoneOffset()*60000); return local.toISOString().slice(0,16); }
  function formatDateInput(value) { return formatLocal(value).slice(0,10); }
  function displayDate(value) { return value ? new Date(value).toLocaleString() : '—'; }
  function isoFromLocal(value) { if(!value) return null; const date=new Date(value); if(Number.isNaN(date.getTime())) throw new Error(`Invalid date: ${value}`); return date.toISOString(); }
  function validTime(value) { return /^([01]\d|2[0-3]):[0-5]\d$/.test(String(value||'')); }
  function timeSettings() { const saved=GM_getValue(TIME_SETTINGS_KEY,{}); return {due:validTime(saved?.due)?saved.due:'23:59',late:validTime(saved?.late)?saved.late:'23:59'}; }
  function isoFromDateAndTime(value,time) { if(!value) return null; const clock=validTime(time)?time:'23:59'; const date=new Date(`${value}T${clock}:00`); if(Number.isNaN(date.getTime())) throw new Error(`Invalid date or time: ${value} ${clock}`); return date.toISOString(); }
  function csrfToken() { const raw=document.cookie.split('; ').find((part)=>part.startsWith('_csrf_token='))?.split('=').slice(1).join('='); return raw ? decodeURIComponent(raw) : ''; }
  function nextLink(header) { return String(header||'').split(',').find((p)=>/rel="next"/.test(p))?.match(/<([^>]+)>/)?.[1] || ''; }

  async function canvasRequest(url, options={}) {
    const headers={ Accept:'application/json', ...(options.headers||{}) };
    if(options.method && options.method !== 'GET') { headers['Content-Type']='application/json'; headers['X-CSRF-Token']=csrfToken(); }
    const response=await fetch(url,{ credentials:'same-origin',...options,headers });
    if(!response.ok) throw new Error(`Canvas ${response.status}: ${(await response.text()).slice(0,300)}`);
    return response.status===204 ? null : response.json();
  }
  async function canvasPages(url) {
    const rows=[]; let next=url;
    while(next){ const response=await fetch(next,{credentials:'same-origin',headers:{Accept:'application/json'}}); if(!response.ok) throw new Error(`Canvas ${response.status}: ${(await response.text()).slice(0,300)}`); rows.push(...await response.json()); next=nextLink(response.headers.get('Link')); }
    return rows;
  }
  function gsErrorMessage(response) { const doc=parseHtml(response.responseText||''), visible=doc.querySelector('.flash--error,.alert-error,[role="alert"],.form--error')?.textContent?.replace(/\s+/g,' ').trim(); if(visible)return visible; if(response.status===422)return 'Gradescope rejected the extension request (422). Refresh the Gradescope connection and try again.'; return `Gradescope request failed (${response.status}).`; }
  function gsRequest(method,path,data=null) {
    return new Promise((resolve,reject)=>GM_xmlhttpRequest({
      method,url:`${GS_BASE}${path}`,data:data?JSON.stringify(data):undefined,
      headers:{Accept:'text/html,application/json','Content-Type':'application/json',...(state.gsCsrf?{'X-CSRF-Token':state.gsCsrf,'X-Requested-With':'XMLHttpRequest'}:{})},anonymous:false,timeout:30000,
      onload:(r)=>r.status>=200&&r.status<300?resolve(r):reject(new Error(gsErrorMessage(r))),
      onerror:()=>reject(new Error('Gradescope request failed. Check Tampermonkey site permissions.')),
      ontimeout:()=>reject(new Error('Gradescope request timed out.')),
    }));
  }
  function parseHtml(text) { return new DOMParser().parseFromString(text,'text/html'); }
  function readJsonAttr(node,name) { try{return JSON.parse(node?.getAttribute(name)||'{}');}catch(_){return{};} }

  async function discoverGradescope() {
    const account=await gsRequest('GET','/account'); const doc=parseHtml(account.responseText);
    if(doc.querySelector('form[action*="/login"], input[name="session[email]"]')) throw new Error('Sign into Gradescope in this browser, then retry.');
    state.gsCsrf=doc.querySelector('meta[name="csrf-token"]')?.content||'';
    const courses=Array.from(doc.querySelectorAll('a.courseBox[href^="/courses/"]')).map((link)=>({
      id:link.getAttribute('href').match(/\/courses\/(\d+)/)?.[1],
      code:link.querySelector('.courseBox--shortname')?.textContent.trim()||'', name:link.querySelector('.courseBox--name')?.textContent.trim()||'',
    })).filter((c)=>c.id);
    const saved=String(GM_getValue(`cgde-gs-course-${courseId}`,'')||'');
    let match=courses.find((c)=>c.id===saved);
    if(!match){ const canvasKeys=[normalize(state.course.name),normalize(state.course.course_code)].filter(Boolean); const hits=courses.filter((c)=>[normalize(c.code),normalize(c.name)].some((g)=>canvasKeys.some((v)=>v===g||v.includes(g)||g.includes(v)))); if(hits.length===1) match=hits[0]; }
    if(!match) return {connected:true,courses,course:null,assignments:[],students:[]};
    return loadGradescopeCourse(match,courses);
  }
  async function loadGradescopeCourse(match,courses=state.gs?.courses||[]) {
    GM_setValue(`cgde-gs-course-${courseId}`,match.id);
    const [assignmentPage,rosterPage]=await Promise.all([gsRequest('GET',`/courses/${match.id}/assignments`),gsRequest('GET',`/courses/${match.id}/memberships`)]);
    const adoc=parseHtml(assignmentPage.responseText), props=readJsonAttr(adoc.querySelector('[data-react-class="AssignmentsTable"]'),'data-react-props');
    const assignments=(props.table_data||[]).filter((a)=>a.type==='assignment').map((a)=>({id:String(a.url||'').split('/').pop(),name:a.title,due:a.submission_window?.due_date,late:a.submission_window?.hard_due_date}));
    const rdoc=parseHtml(rosterPage.responseText), students=Array.from(rdoc.querySelectorAll('tr.rosterRow')).map((row)=>{
      const edit=row.querySelector('button.rosterCell--editIcon'), grade=row.querySelector('button.js-rosterName'); if(!edit||edit.dataset.role!=='0') return null;
      return {email:(edit.dataset.email||'').toLowerCase(),name:readJsonAttr(edit,'data-cm').full_name||edit.dataset.email,id:(grade?.dataset.url||'').match(/user_id=(\d+)/)?.[1]};
    }).filter((s)=>s?.id);
    return {connected:true,courses,course:match,assignments,students};
  }

  async function loadData() {
    setStatus('Loading Canvas course, roster, and assignments…');
    const [course,students,assignments]=await Promise.all([
      canvasRequest(`/api/v1/courses/${courseId}`),
      canvasPages(`/api/v1/courses/${courseId}/users?enrollment_type[]=student&include[]=email&per_page=100`),
      canvasPages(`/api/v1/courses/${courseId}/assignments?include[]=all_dates&order_by=due_at&per_page=100`),
    ]);
    state.course=course; state.students=students.sort((a,b)=>a.sortable_name.localeCompare(b.sortable_name)); state.assignments=assignments.filter((a)=>a.due_at);
    fillStudents(); fillAssignments(); setStatus(`Loaded ${state.students.length} students and ${state.assignments.length} dated assignments.`);
    try { state.gs=await discoverGradescope(); renderGradescope(); }
    catch(error){ state.gs=null; renderGradescope(error.message); }
  }

  function buildUi() {
    const defaultTimes=timeSettings();
    const style=el('style'); style.textContent=css; document.head.append(style);
    const launch=el('button','cgde-launch','Student deadlines'); launch.type='button'; launch.addEventListener('click',open); document.body.append(launch);
    const backdrop=el('div','cgde-backdrop cgde-hidden'); backdrop.id='cgde-backdrop'; backdrop.innerHTML=`
      <section class="cgde-modal" role="dialog" aria-modal="true" aria-labelledby="cgde-title">
        <header class="cgde-header"><div class="cgde-title-wrap"><p class="cgde-eyebrow">Canvas + Gradescope</p><h2 id="cgde-title">Student deadlines</h2><p class="cgde-subtitle">Review current dates, prepare changes, and verify both systems.</p></div><button class="cgde-close" aria-label="Close">×</button></header>
        <div class="cgde-body">
          <div class="cgde-grid">
            <section class="cgde-card"><h3>1. Students</h3><label class="cgde-field"><span>Search by any name or email tokens</span><input id="cgde-student-search" class="cgde-input" type="search" placeholder="e.g. maya chen or mchen"></label><div id="cgde-student-selected" class="cgde-student-chips"><span class="cgde-student-empty">No students selected</span></div><div id="cgde-student-results" class="cgde-search-results cgde-hidden"></div><div id="cgde-gs" class="cgde-muted" style="margin-top:9px">Checking Gradescope…</div><label id="cgde-gs-course-field" class="cgde-field cgde-hidden" style="margin-top:8px"><span>Gradescope course</span><select id="cgde-gs-course" class="cgde-select"><option value="">Choose the matching course…</option></select></label></section>
            <section class="cgde-card"><h3>2. Date method</h3><div class="cgde-modes">
              <label class="cgde-field" style="min-width:190px"><span>Quick preset</span><select id="cgde-preset" class="cgde-select"><option value="">Custom</option><option value="shift-2">Shift +2 days</option><option value="shift-3">Shift +3 days</option><option value="shift-7">Shift +7 days</option><option value="same-none">Shared due date; no late window</option><option value="same-24">Shared due date; 24-hour late window</option></select></label>
              <label class="cgde-inline"><input type="radio" name="cgde-mode" value="shift" checked> Shift by <input id="cgde-days" class="cgde-input" type="number" step="0.25" value="3"> days</label>
              <label class="cgde-inline"><input type="radio" name="cgde-mode" value="same"> Same dates:</label>
              <label class="cgde-field"><span>Due date</span><input id="cgde-same-due" class="cgde-input cgde-date" type="date"></label>
              <label class="cgde-field"><span>Available until / late</span><input id="cgde-same-late" class="cgde-input cgde-date" type="date"></label>
              <label class="cgde-field"><span>Default due time</span><input id="cgde-due-time" class="cgde-input" type="time" value="${defaultTimes.due}"></label>
              <label class="cgde-field"><span>Default late time</span><input id="cgde-late-time" class="cgde-input" type="time" value="${defaultTimes.late}"></label>
              <label class="cgde-inline"><input type="radio" name="cgde-mode" value="manual"> Manual table dates</label>
              <button id="cgde-find-repairs" class="cgde-button" type="button">Find & prepare Gradescope repairs</button><input id="cgde-gs-only" type="checkbox" hidden><div id="cgde-repair-banner" class="cgde-repair-banner cgde-hidden"><span>✓</span><strong>Gradescope repair mode — Canvas will not be changed</strong><button id="cgde-exit-repair" class="cgde-button" type="button">Exit repair mode</button></div>
              <label class="cgde-field" style="flex-basis:100%;margin:4px 0 0"><span>Optional history note — keep it general; do not enter medical details</span><input id="cgde-note" class="cgde-input" type="text" maxlength="160" placeholder="e.g. Instructor-approved extension"></label>
            </div></section>
          </div>
          <section class="cgde-card cgde-assignment-search"><h3>3. Find assignments</h3><div class="cgde-assignment-toolbar"><label class="cgde-field"><span>Search by any title tokens; click a result to add it</span><input id="cgde-assignment-search" class="cgde-input" type="search" placeholder="e.g. homework graph or exam 2"></label><label class="cgde-inline"><input id="cgde-show-all" type="checkbox"> Show all assignments</label></div><div id="cgde-assignment-results" class="cgde-search-results cgde-hidden"></div></section>
          <div class="cgde-queue-heading"><h3>Selected assignment queue <span id="cgde-queue-count" class="cgde-muted">(0)</span></h3><button id="cgde-clear-queue" class="cgde-button" type="button">Clear queue</button></div>
          <div class="cgde-table-wrap"><table class="cgde-table"><thead><tr><th>Remove</th><th>Assignment</th><th>Student's Canvas due</th><th>Student's Canvas until</th><th>Student's Gradescope due</th><th>Student's Gradescope late</th><th>New due<br><small id="cgde-due-time-label">${formatClock(defaultTimes.due)}</small></th><th>New until<br><small id="cgde-late-time-label">${formatClock(defaultTimes.late)}</small></th></tr></thead><tbody id="cgde-rows"><tr><td colspan="8">Search above and click assignments to add them.</td></tr></tbody></table></div>
          <details id="cgde-history" class="cgde-history"><summary>Update history</summary><div id="cgde-history-body" class="cgde-history-body"></div></details>
        </div>
        <section id="cgde-summary" class="cgde-summary cgde-hidden" aria-live="polite"></section>
        <footer class="cgde-footer"><span id="cgde-status" class="cgde-status">Ready</span><button id="cgde-stop" class="cgde-button cgde-hidden">Stop after current item</button><button id="cgde-gs-retry" class="cgde-button">Retry Gradescope</button><button id="cgde-preview" class="cgde-button">Preview</button><button id="cgde-apply" class="cgde-button cgde-primary" disabled>Apply confirmed changes</button></footer>
      </section>`;
    document.body.append(backdrop);
    backdrop.querySelector('.cgde-close').addEventListener('click',close); backdrop.addEventListener('click',(e)=>{if(e.target===backdrop)close();});
    document.getElementById('cgde-preview').addEventListener('click',preview);
    document.getElementById('cgde-apply').addEventListener('click',applyPlans);
    document.getElementById('cgde-stop').addEventListener('click',()=>{state.stopRequested=true;const button=document.getElementById('cgde-stop');button.disabled=true;button.textContent='Stopping after current item…';});
    document.getElementById('cgde-gs-retry').addEventListener('click',retryGradescope);
    document.getElementById('cgde-gs-course').addEventListener('change',chooseGradescopeCourse);
    document.getElementById('cgde-student-search').addEventListener('input',renderStudentResults);
    document.getElementById('cgde-student-search').addEventListener('focus',renderStudentResults);
    document.getElementById('cgde-assignment-search').addEventListener('input',renderAssignmentResults);
    document.getElementById('cgde-assignment-search').addEventListener('focus',renderAssignmentResults);
    document.getElementById('cgde-show-all').addEventListener('change',renderAssignmentResults);
    document.getElementById('cgde-clear-queue').addEventListener('click',()=>{state.selectedAssignments.clear();renderQueue();invalidate();});
    document.getElementById('cgde-history').addEventListener('toggle',()=>{if(document.getElementById('cgde-history').open)renderHistory();});
    document.querySelectorAll('input[name="cgde-mode"],#cgde-days,#cgde-same-due,#cgde-same-late').forEach((node)=>node.addEventListener('change',invalidate));
    document.getElementById('cgde-find-repairs').addEventListener('click',autoFindRepairs);
    document.getElementById('cgde-exit-repair').addEventListener('click',()=>setRepairMode(false));
    document.getElementById('cgde-preset').addEventListener('change',applyPreset);
    document.getElementById('cgde-same-due').addEventListener('change',refreshPresetLateDate);
    document.getElementById('cgde-due-time').addEventListener('change',saveDefaultTimes);
    document.getElementById('cgde-late-time').addEventListener('change',saveDefaultTimes);
    document.addEventListener('keydown',(event)=>{if(event.key==='Escape'&&!backdrop.classList.contains('cgde-hidden'))close();});
  }
  function open(){ document.getElementById('cgde-backdrop').classList.remove('cgde-hidden');document.body.dataset.cgdeOverflow=document.body.style.overflow||'';document.body.style.overflow='hidden';setTimeout(()=>document.getElementById('cgde-student-search').focus(),60);if(!state.course) loadData().catch(showError); }
  function close(){ document.getElementById('cgde-backdrop').classList.add('cgde-hidden');document.body.style.overflow=document.body.dataset.cgdeOverflow||''; }
  function setStatus(text,kind=''){ const node=document.getElementById('cgde-status'); node.textContent=text; node.className=`cgde-status ${kind}`; }
  function showError(error){ setStatus(error.message||String(error),'cgde-error'); document.getElementById('cgde-apply').disabled=true; }
  function invalidate(){ document.getElementById('cgde-apply').disabled=true; state.plans=[];state.skipped=[]; }
  function setRepairMode(enabled){document.getElementById('cgde-gs-only').checked=enabled;document.getElementById('cgde-repair-banner').classList.toggle('cgde-hidden',!enabled);invalidate();}
  function selectMode(value){const radio=document.querySelector(`input[name="cgde-mode"][value="${value}"]`);if(radio)radio.checked=true;}
  function formatClock(value){if(!validTime(value))return '11:59 PM';const [hours,minutes]=value.split(':').map(Number),suffix=hours>=12?'PM':'AM';return `${hours%12||12}:${String(minutes).padStart(2,'0')} ${suffix}`;}
  function saveDefaultTimes(){const due=document.getElementById('cgde-due-time').value,late=document.getElementById('cgde-late-time').value;if(!validTime(due)||!validTime(late)){showError(new Error('Choose valid default due and late times.'));return;}GM_setValue(TIME_SETTINGS_KEY,{due,late});document.getElementById('cgde-due-time-label').textContent=formatClock(due);document.getElementById('cgde-late-time-label').textContent=formatClock(late);invalidate();setStatus(`Default times saved: due ${formatClock(due)}, late ${formatClock(late)}.`,'cgde-ok');}
  function refreshPresetLateDate(){if(document.getElementById('cgde-preset').value!=='same-24')return;const due=document.getElementById('cgde-same-due').value;if(!due)return;const date=new Date(`${due}T12:00:00`);date.setDate(date.getDate()+1);document.getElementById('cgde-same-late').value=formatDateInput(date);invalidate();}
  function applyPreset(){const value=document.getElementById('cgde-preset').value;if(value.startsWith('shift-')){selectMode('shift');document.getElementById('cgde-days').value=value.split('-')[1];}else if(value==='same-none'){selectMode('same');document.getElementById('cgde-same-late').value='';}else if(value==='same-24'){selectMode('same');refreshPresetLateDate();}invalidate();}
  function tokenMatch(value,query){ const haystack=normalize(value),tokens=normalize(query).split(' ').filter(Boolean); return tokens.every((token)=>haystack.includes(token)); }
  function fillStudents(){ document.getElementById('cgde-student-search').placeholder=`Search ${state.students.length} students by name or email`; renderStudentResults(); }
  function selectedStudents(){return Array.from(state.selectedStudentIds).map((id)=>state.students.find((student)=>String(student.id)===String(id))).filter(Boolean);}
  function renderStudentResults(){ const input=document.getElementById('cgde-student-search'),box=document.getElementById('cgde-student-results'),query=input.value.trim(); if(!query){box.classList.add('cgde-hidden');box.innerHTML='';return;} const hits=state.students.filter((s)=>!state.selectedStudentIds.has(String(s.id))&&tokenMatch(`${s.name} ${s.sortable_name||''} ${s.email||''}`,query)).slice(0,30); box.innerHTML=hits.map((s)=>`<button type="button" class="cgde-search-result" data-id="${s.id}"><span><strong>${escapeHtml(s.name)}</strong><small>${escapeHtml(s.email||'No email')}</small></span></button>`).join('')||'<div class="cgde-empty-search">No unselected students match every search token.</div>';box.classList.remove('cgde-hidden');box.querySelectorAll('button').forEach((button)=>button.addEventListener('click',()=>selectStudent(button.dataset.id))); }
  function renderSelectedStudents(){const selected=document.getElementById('cgde-student-selected'),students=selectedStudents();selected.innerHTML=students.map((student)=>`<span class="cgde-student-chip">${escapeHtml(student.name)}<button type="button" data-id="${student.id}" aria-label="Remove ${escapeHtml(student.name)}">×</button></span>`).join('')||'<span class="cgde-student-empty">No students selected</span>';selected.querySelectorAll('button').forEach((button)=>button.addEventListener('click',()=>removeStudent(button.dataset.id)));}
  function selectStudent(id){const student=state.students.find((s)=>String(s.id)===String(id));if(!student)return;state.selectedStudentIds.add(String(student.id));state.student=selectedStudents()[0]||null;state.current.clear();renderSelectedStudents();document.getElementById('cgde-student-search').value='';document.getElementById('cgde-student-results').classList.add('cgde-hidden');renderQueue();invalidate();}
  function removeStudent(id){state.selectedStudentIds.delete(String(id));state.student=selectedStudents()[0]||null;state.current.clear();renderSelectedStudents();renderQueue();renderStudentResults();invalidate();}
  function assignmentMap(){const value=GM_getValue(`cgde-gs-assignment-map-${courseId}`,{});return value&&typeof value==='object'?value:{};}
  function saveAssignmentMapping(canvasAssignmentId,gradescopeAssignmentId){const map=assignmentMap();if(gradescopeAssignmentId)map[String(canvasAssignmentId)]=String(gradescopeAssignmentId);else delete map[String(canvasAssignmentId)];GM_setValue(`cgde-gs-assignment-map-${courseId}`,map);state.current.clear();renderAssignmentResults();renderQueue();invalidate();}
  function gsMatch(assignment){const explicit=assignmentMap()[String(assignment.id)],mapped=explicit?state.gs?.assignments.find((item)=>String(item.id)===String(explicit)):null;if(mapped)return mapped; const hits=state.gs?.assignments.filter((a)=>normalize(a.name)===normalize(assignment.name))||[]; return hits.length===1?hits[0]:null; }
  function fillAssignments(){ document.getElementById('cgde-assignment-search').placeholder=`Search ${state.assignments.length} dated assignments`;renderAssignmentResults();renderQueue(); }
  function renderAssignmentResults(){ const input=document.getElementById('cgde-assignment-search'),box=document.getElementById('cgde-assignment-results'),showAll=document.getElementById('cgde-show-all').checked,query=input.value.trim(); if(!query&&!showAll){box.classList.add('cgde-hidden');box.innerHTML='';return;} const hits=state.assignments.filter((a)=>!state.selectedAssignments.has(String(a.id))&&tokenMatch(a.name,query)).slice(0,showAll?200:40);box.innerHTML=hits.map((a)=>`<button type="button" class="cgde-search-result" data-id="${a.id}"><span><strong>${escapeHtml(a.name)}</strong><small>Due ${escapeHtml(displayDate(a.due_at))}${gsMatch(a)?' • Gradescope matched':''}</small></span></button>`).join('')||'<div class="cgde-empty-search">No unselected assignments match every search token.</div>';box.classList.remove('cgde-hidden');box.querySelectorAll('button').forEach((button)=>button.addEventListener('click',()=>addAssignment(button.dataset.id))); }
  function addAssignment(id){state.selectedAssignments.add(String(id));renderQueue();renderAssignmentResults();invalidate();}
  function removeAssignment(id){state.selectedAssignments.delete(String(id));renderQueue();renderAssignmentResults();invalidate();}
  function currentCell(value,fallback,label,specific=Boolean(value)){return `<span>${escapeHtml(displayDate(specific?value:fallback))}</span><small>${specific?label:'Class default'}</small>`;}
  function renderQueue(){ const body=document.getElementById('cgde-rows'),students=selectedStudents(),multi=students.length>1,assignments=Array.from(state.selectedAssignments).map((id)=>state.assignments.find((a)=>String(a.id)===id)).filter(Boolean);document.getElementById('cgde-queue-count').textContent=`(${assignments.length})`;body.innerHTML=assignments.map((a)=>{const current=!multi?state.current.get(String(a.id)):null,currentDisplay=multi?`<span>${students.length} students selected</span><small>Preview shows each individual action</small>`:'Loading…',match=gsMatch(a),options=(state.gs?.assignments||[]).map((item)=>`<option value="${item.id}"${match&&String(item.id)===String(match.id)?' selected':''}>${escapeHtml(item.name)}</option>`).join('');return `<tr data-id="${a.id}"><td><button type="button" class="cgde-remove" data-id="${a.id}" aria-label="Remove ${escapeHtml(a.name)}">× Remove</button></td><td class="cgde-name">${escapeHtml(a.name)}<small>${escapeHtml(match?.name||'No Gradescope match')}</small>${state.gs?.course?`<select class="cgde-map-select" data-id="${a.id}" aria-label="Gradescope mapping for ${escapeHtml(a.name)}"><option value="">Auto-match by title</option>${options}</select>`:''}</td><td class="cgde-system-date cgde-canvas-due">${current?currentCell(current.canvasDue,a.due_at,'Student override',current.canvasOverride):currentDisplay}</td><td class="cgde-system-date cgde-canvas-late">${current?currentCell(current.canvasLate,a.lock_at,'Student override',current.canvasOverride):currentDisplay}</td><td class="cgde-system-date cgde-gs-due">${current?currentCell(current.gsDue,match?.due,'Student extension',current.gsExtension):currentDisplay}</td><td class="cgde-system-date cgde-gs-late">${current?currentCell(current.gsLate,match?.late,'Student extension',current.gsExtension):currentDisplay}</td><td><input class="cgde-new-due" type="date" value="${formatDateInput(current?.canvasDue||a.due_at)}"></td><td><input class="cgde-new-late" type="date" value="${formatDateInput(current?.canvasLate??a.lock_at)}"></td></tr>`;}).join('')||'<tr><td colspan="8">Search above and click assignments to add them.</td></tr>';body.querySelectorAll('input').forEach((n)=>n.addEventListener('change',invalidate));body.querySelectorAll('.cgde-remove').forEach((b)=>b.addEventListener('click',()=>removeAssignment(b.dataset.id)));body.querySelectorAll('.cgde-map-select').forEach((select)=>select.addEventListener('change',()=>saveAssignmentMapping(select.dataset.id,select.value)));if(students.length===1)assignments.forEach(loadCurrentDeadlines); }
  function renderGradescope(error=''){ const node=document.getElementById('cgde-gs'),field=document.getElementById('cgde-gs-course-field'),select=document.getElementById('cgde-gs-course'); if(error){node.className='cgde-error';node.textContent=error;document.getElementById('cgde-gs-retry').classList.remove('cgde-hidden');field.classList.add('cgde-hidden');}else if(state.gs?.course){node.className='cgde-ok';node.textContent=`Gradescope: ${state.gs.course.code} — ${state.gs.course.name}`;document.getElementById('cgde-gs-retry').classList.add('cgde-hidden');field.classList.remove('cgde-hidden');}else{node.className='cgde-warn';node.textContent=state.gs?.connected?'Choose the matching Gradescope course below. Canvas remains available.':'Gradescope unavailable; Canvas-only mode.';document.getElementById('cgde-gs-retry').classList.remove('cgde-hidden');field.classList.toggle('cgde-hidden',!state.gs?.courses?.length);} if(state.gs?.courses?.length){const current=state.gs.course?.id||'';select.innerHTML='<option value="">Choose the matching course…</option>'+state.gs.courses.map((c)=>`<option value="${c.id}"${c.id===current?' selected':''}>${escapeHtml(c.code)} — ${escapeHtml(c.name)}</option>`).join('');}state.current.clear();renderAssignmentResults();renderQueue(); }
  async function chooseGradescopeCourse(){ const id=document.getElementById('cgde-gs-course').value;if(!id)return;const course=state.gs?.courses.find((c)=>c.id===id);if(!course)return;setStatus(`Loading Gradescope course ${course.code}…`);try{state.gs=await loadGradescopeCourse(course,state.gs.courses);renderGradescope();renderQueue();setStatus(`Gradescope course mapped; ${state.gs.assignments.length} assignments loaded.`,'cgde-ok');}catch(e){renderGradescope(e.message);showError(e);} }
  async function retryGradescope(){ setStatus('Checking Gradescope…'); try{state.gs=await discoverGradescope();renderGradescope();setStatus('Gradescope check complete.');}catch(e){state.gs=null;renderGradescope(e.message);setStatus('Canvas remains available.','cgde-warn');} }

  async function getOverride(assignmentId,studentId){ const rows=await canvasPages(`/api/v1/courses/${courseId}/assignments/${assignmentId}/overrides?per_page=100`); return rows.find((o)=>(o.student_ids||[]).map(String).includes(String(studentId)))||null; }
  function extensionRows(text){const doc=parseHtml(text);return Array.from(doc.querySelectorAll('[data-react-class="EditExtension"]')).map((node)=>readJsonAttr(node,'data-react-props').override).filter(Boolean);}
  function extensionEntries(text){const doc=parseHtml(text);return Array.from(doc.querySelectorAll('[data-react-class="EditExtension"]')).map((node)=>readJsonAttr(node,'data-react-props')).filter((entry)=>entry.override);}
  function gradescopeStudentFor(student){if(!state.gs?.students||!student?.email)return null;const hits=state.gs.students.filter((entry)=>entry.email===(student.email||'').toLowerCase());return hits.length===1?hits[0]:null;}
  async function getGradescopeExtension(assignmentId,userId){if(!assignmentId||!userId)return null;const page=await gsRequest('GET',`/courses/${state.gs.course.id}/assignments/${assignmentId}/extensions`);return extensionRows(page.responseText).find((item)=>String(item.user_id)===String(userId))||null;}
  async function autoFindRepairs(){if(selectedStudents().length!==1){showError(new Error('Select exactly one student for automatic Gradescope repair.'));return;}if(!state.gs?.course){showError(new Error('Choose and connect the matching Gradescope course first.'));return;}const email=(state.student.email||'').toLowerCase(),gsStudents=state.gs.students.filter((student)=>student.email===email);if(gsStudents.length!==1){showError(new Error('The selected student email does not uniquely match the Gradescope roster.'));return;}const candidates=state.assignments.map((assignment)=>({assignment,gs:gsMatch(assignment)})).filter((item)=>item.gs),button=document.getElementById('cgde-find-repairs');button.disabled=true;state.selectedAssignments.clear();state.current.clear();const needed=[],errors=[];try{for(let start=0;start<candidates.length;start+=5){const batch=candidates.slice(start,start+5);setStatus(`Scanning Gradescope extensions ${start+1}–${Math.min(start+batch.length,candidates.length)} of ${candidates.length}…`);const checked=await Promise.all(batch.map(async({assignment,gs})=>{try{const [override,extension]=await Promise.all([getOverride(assignment.id,state.student.id),getGradescopeExtension(gs.id,gsStudents[0].id)]);if(!override?.due_at)return null;const expectedLate=override.lock_at||override.due_at,actualDue=extension?.settings?.due_date?.value,actualLate=extension?.settings?.hard_due_date?.value;if(!extension||!closeEnough(actualDue,override.due_at)||!closeEnough(actualLate,expectedLate))return assignment;state.current.set(String(assignment.id),{canvasOverride:true,canvasDue:override.due_at,canvasLate:override.lock_at||null,gsExtension:true,gsDue:actualDue,gsLate:actualLate});return null;}catch(error){errors.push(`${assignment.name}: ${error.message}`);return null;}}));needed.push(...checked.filter(Boolean));}needed.forEach((assignment)=>state.selectedAssignments.add(String(assignment.id)));setRepairMode(true);renderQueue();renderAssignmentResults();if(needed.length)setStatus(`Found ${needed.length} missing or mismatched Gradescope extension(s). Review the queue, then Preview.`,'cgde-ok');else setStatus(errors.length?`No repairs queued; ${errors.length} assignment(s) could not be checked.`:'No Gradescope repairs are needed for this student.','cgde-ok');if(errors.length)console.warn('Gradescope repair scan errors',errors);}catch(error){showError(error);}finally{button.disabled=false;}}
  async function loadCurrentDeadlines(assignment){const key=String(assignment.id),studentId=String(state.student?.id||'');if(!studentId||state.current.has(key)||selectedStudents().length!==1)return;const gsAssignment=gsMatch(assignment),gsStudent=state.gs?.students.filter((s)=>s.email===(state.student.email||'').toLowerCase());try{const [override,extension]=await Promise.all([getOverride(assignment.id,studentId),gsAssignment&&gsStudent?.length===1?getGradescopeExtension(gsAssignment.id,gsStudent[0].id):null]);if(String(state.student?.id||'')!==studentId||selectedStudents().length!==1)return;state.current.set(key,{canvasOverride:Boolean(override),canvasDue:override?.due_at||null,canvasLate:override?.lock_at||null,gsExtension:Boolean(extension),gsDue:extension?.settings?.due_date?.value||null,gsLate:extension?.settings?.hard_due_date?.value||null});const row=document.querySelector(`#cgde-rows tr[data-id="${CSS.escape(key)}"]`);if(row){row.querySelector('.cgde-canvas-due').innerHTML=currentCell(override?.due_at,assignment.due_at,'Student override',Boolean(override));row.querySelector('.cgde-canvas-late').innerHTML=currentCell(override?.lock_at,assignment.lock_at,'Student override',Boolean(override));row.querySelector('.cgde-gs-due').innerHTML=currentCell(extension?.settings?.due_date?.value,gsAssignment?.due,'Student extension',Boolean(extension));row.querySelector('.cgde-gs-late').innerHTML=currentCell(extension?.settings?.hard_due_date?.value,gsAssignment?.late,'Student extension',Boolean(extension));row.querySelector('.cgde-new-due').value=formatDateInput(override?.due_at||assignment.due_at);row.querySelector('.cgde-new-late').value=formatDateInput(override?override.lock_at:assignment.lock_at);}}catch(error){if(selectedStudents().length!==1)return;const row=document.querySelector(`#cgde-rows tr[data-id="${CSS.escape(key)}"]`);if(row)row.querySelectorAll('.cgde-system-date').forEach((cell)=>cell.innerHTML=`<span class="cgde-error">Unavailable</span><small>${escapeHtml(error.message)}</small>`);}}

  function readHistory(){const value=GM_getValue(HISTORY_KEY,[]);return Array.isArray(value)?value:[];}
  function writeHistory(results){const history=readHistory(),byStudent=new Map(),note=document.getElementById('cgde-note').value.trim();results.forEach((result)=>{if(!byStudent.has(result.studentId))byStudent.set(result.studentId,[]);byStudent.get(result.studentId).push(result);});for(const [studentId,items] of byStudent){const student=state.students.find((entry)=>String(entry.id)===String(studentId));history.unshift({timestamp:new Date().toISOString(),courseId,courseName:state.course?.name||'',note,student:{id:student.id,name:student.name,email:student.email||''},items:items.map((r)=>({assignmentId:r.assignmentId,gradescopeId:r.gradescopeId,name:r.assignmentName,due:r.due,late:r.late,canvas:r.canvas,gradescope:r.gs,errors:r.errors,previousCanvas:r.previousCanvas,previousGradescope:r.previousGradescope}))});}GM_setValue(HISTORY_KEY,history.slice(0,100));renderHistory();}
  function canvasHistoryStatus(value){return value===true?'updated':value==='unchanged'?'already correct':value===null?'unchanged':'failed';}
  function gradescopeHistoryStatus(value){return value===true?'extension verified':value==='unchanged'?'already correct':value===null?'not matched':'failed';}
  function csvCell(value){const text=String(value??'');return /[",\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text;}
  function exportHistoryCsv(){const runs=readHistory().filter((run)=>String(run.courseId)===String(courseId)),headers=['Timestamp','Course','Student','Email','Note','Assignment','Previous Canvas due','Previous Canvas until','New due','New until','Canvas result','Previous Gradescope due','Previous Gradescope late','Gradescope result','Errors','Undone at'],rows=[headers];runs.forEach((run)=>run.items.forEach((item)=>rows.push([run.timestamp,run.courseName,run.student.name,run.student.email,run.note||'',item.name,item.previousCanvas?.due||'',item.previousCanvas?.late||'',item.due||'',item.late||'',canvasHistoryStatus(item.canvas),item.previousGradescope?.due||'',item.previousGradescope?.late||'',gradescopeHistoryStatus(item.gradescope),(item.errors||[]).join('; '),run.undoneAt||''])));const csv=rows.map((row)=>row.map(csvCell).join(',')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`deadline-history-course-${courseId}-${new Date().toISOString().slice(0,10)}.csv`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function renderHistory(){const body=document.getElementById('cgde-history-body'),runs=readHistory().filter((run)=>String(run.courseId)===String(courseId));body.innerHTML=`<div style="display:flex;justify-content:flex-end;padding:6px 0"><button id="cgde-export-history" class="cgde-button" type="button"${runs.length?'':' disabled'}>Export course history CSV</button></div>`+(runs.map((run,index)=>{const failed=run.items.filter((item)=>item.gradescope===false&&item.gradescopeId),undoable=!run.undoneAt&&run.items.some((item)=>(item.canvas===true&&item.previousCanvas)||(item.gradescope===true&&item.previousGradescope));return `<article class="cgde-history-run"><div class="cgde-history-head"><div><strong>${escapeHtml(run.student.name)}</strong><div class="cgde-summary-note">${escapeHtml(new Date(run.timestamp).toLocaleString())} • ${run.items.length} assignment(s)${run.undoneAt?' • Undone '+escapeHtml(new Date(run.undoneAt).toLocaleString()):''}</div>${run.note?`<div class="cgde-summary-note">Note: ${escapeHtml(run.note)}</div>`:''}</div><div>${failed.length?`<button type="button" class="cgde-button cgde-history-retry" data-index="${index}">Restore ${failed.length} Gradescope failure(s)</button>`:''}${undoable?` <button type="button" class="cgde-button cgde-history-undo" data-index="${index}">Undo successful changes</button>`:''}</div></div><ul class="cgde-history-items">${run.items.map((item)=>`<li>${escapeHtml(item.name)} — Canvas ${canvasHistoryStatus(item.canvas)}; Gradescope ${gradescopeHistoryStatus(item.gradescope)} • Due ${escapeHtml(displayDate(item.due))}</li>`).join('')}</ul></article>`;}).join('')||'<div class="cgde-muted">No update history for this Canvas course yet.</div>');body.querySelector('#cgde-export-history').addEventListener('click',exportHistoryCsv);body.querySelectorAll('.cgde-history-retry').forEach((button)=>button.addEventListener('click',()=>restoreHistory(runs[Number(button.dataset.index)])));body.querySelectorAll('.cgde-history-undo').forEach((button)=>button.addEventListener('click',()=>undoHistory(runs[Number(button.dataset.index)])));}
  function restoreHistory(run){const student=state.students.find((s)=>String(s.id)===String(run.student.id))||state.students.find((s)=>(s.email||'').toLowerCase()===(run.student.email||'').toLowerCase());if(!student){showError(new Error('The history student is not in the current Canvas roster.'));return;}state.selectedStudentIds.clear();selectStudent(student.id);state.selectedAssignments.clear();run.items.filter((item)=>item.gradescope===false&&item.gradescopeId&&state.assignments.some((a)=>String(a.id)===String(item.assignmentId))).forEach((item)=>state.selectedAssignments.add(String(item.assignmentId)));setRepairMode(true);renderQueue();document.getElementById('cgde-history').open=false;setStatus('Gradescope failures restored. Preview will copy current Canvas override dates without changing Canvas.','cgde-ok');}
  async function deleteCanvasOverride(assignmentId,overrideId){return canvasRequest(`/api/v1/courses/${courseId}/assignments/${assignmentId}/overrides/${overrideId}`,{method:'DELETE'});}
  async function deleteGradescopeExtension(assignmentId,userId){const page=await gsRequest('GET',`/courses/${state.gs.course.id}/assignments/${assignmentId}/extensions`),entry=extensionEntries(page.responseText).find((item)=>String(item.override.user_id)===String(userId));if(!entry)return true;if(!entry.deletePath)throw new Error('Gradescope did not provide an extension removal path.');await gsRequest('DELETE',entry.deletePath);return true;}
  function markHistoryUndone(run){const history=readHistory(),match=history.find((entry)=>entry.timestamp===run.timestamp&&String(entry.student?.id)===String(run.student.id));if(match)match.undoneAt=new Date().toISOString();GM_setValue(HISTORY_KEY,history);renderHistory();}
  async function undoHistory(run){if(!confirm(`Undo the successful changes from ${new Date(run.timestamp).toLocaleString()} for ${run.student.name}?\n\nThis restores prior student deadlines and removes overrides/extensions that this run created.`))return;const student=state.students.find((entry)=>String(entry.id)===String(run.student.id))||run.student,results=[];for(const item of run.items){const errors=[];setStatus(`Undoing ${student.name} — ${item.name}…`);if(item.canvas===true&&item.previousCanvas){try{const current=await getOverride(item.assignmentId,student.id);if(item.previousCanvas.exists){await saveCanvas({student,assignment:{id:item.assignmentId},existing:current,due:item.previousCanvas.due,late:item.previousCanvas.late});}else if(current){await deleteCanvasOverride(item.assignmentId,current.id);}}catch(error){errors.push(`Canvas: ${error.message}`);}}if(item.gradescope===true&&item.previousGradescope&&item.gradescopeId){try{const gsStudent=gradescopeStudentFor(student);if(!gsStudent)throw new Error('student email did not uniquely match');if(item.previousGradescope.exists){await saveGradescope({student,gs:{id:item.gradescopeId},due:item.previousGradescope.due,late:item.previousGradescope.late});}else{await deleteGradescopeExtension(item.gradescopeId,gsStudent.id);}}catch(error){errors.push(`Gradescope: ${error.message}`);}}results.push({name:item.name,errors});}const failures=results.filter((result)=>result.errors.length);if(!failures.length)markHistoryUndone(run);const section=document.getElementById('cgde-summary');section.innerHTML=`<div class="cgde-summary-head"><h3>Undo summary</h3><button type="button" class="cgde-button" id="cgde-summary-close">Dismiss</button></div>${failures.length?`<div class="cgde-summary-errors"><h4 class="cgde-error">${failures.length} item(s) need attention</h4><ul>${failures.map((result)=>`<li><strong>${escapeHtml(result.name)}</strong><div class="cgde-summary-note">${result.errors.map(escapeHtml).join(' • ')}</div></li>`).join('')}</ul></div>`:`<h4 class="cgde-ok">Prior deadlines restored successfully</h4>`}`;section.classList.remove('cgde-hidden');section.querySelector('#cgde-summary-close').addEventListener('click',()=>section.classList.add('cgde-hidden'));setStatus(failures.length?'Undo finished with errors.':'Undo complete.','cgde-ok');}
  async function makePlans(){
    const students=selectedStudents();if(!students.length) throw new Error('Choose at least one student.'); const rows=Array.from(document.querySelectorAll('#cgde-rows tr[data-id]')); if(!rows.length) throw new Error('Add at least one assignment to the queue.');
    const mode=document.querySelector('input[name="cgde-mode"]:checked').value, repair=document.getElementById('cgde-gs-only').checked,days=Number(document.getElementById('cgde-days').value); if(mode==='shift'&&!repair&&!Number.isFinite(days)) throw new Error('Enter a valid number of days.');
    if(repair&&students.length!==1)throw new Error('Automatic Gradescope repair works with one selected student at a time. Remove the other students before repairing.');
    const plans=[],skipped=[]; setStatus('Resolving existing student overrides…');
    for(const row of rows){ const assignment=state.assignments.find((a)=>String(a.id)===row.dataset.id),gsAssignment=gsMatch(assignment);if(repair&&!gsAssignment){skipped.push({assignment,reason:'No unique Gradescope assignment match'});continue;}for(const student of students){const gsStudent=gradescopeStudentFor(student),[existing,gsExtension]=await Promise.all([getOverride(assignment.id,student.id),gsAssignment&&gsStudent?getGradescopeExtension(gsAssignment.id,gsStudent.id):null]);let due,late;if(!repair&&(existing?.student_ids||[]).length>1){skipped.push({assignment,student,reason:`Shared Canvas override contains ${existing.student_ids.length} students; skipped to protect the other students`});continue;}
        if(repair){if(!existing?.due_at){skipped.push({assignment,reason:`No existing Canvas override for ${student.name}`});continue;}due=existing.due_at;late=existing.lock_at||null;}
        else if(mode==='shift'){ const delta=days*86400000, baseDue=existing?.due_at||assignment.due_at, baseLate=existing?.lock_at??assignment.lock_at; due=new Date(new Date(baseDue).getTime()+delta).toISOString(); late=baseLate?new Date(new Date(baseLate).getTime()+delta).toISOString():null; }
        else if(mode==='same'){ due=isoFromDateAndTime(document.getElementById('cgde-same-due').value,document.getElementById('cgde-due-time').value); late=isoFromDateAndTime(document.getElementById('cgde-same-late').value,document.getElementById('cgde-late-time').value); if(!due)throw new Error('Enter the shared due date.'); }
        else { due=isoFromDateAndTime(row.querySelector('.cgde-new-due').value,document.getElementById('cgde-due-time').value); late=isoFromDateAndTime(row.querySelector('.cgde-new-late').value,document.getElementById('cgde-late-time').value); if(!due)throw new Error(`Enter a due date for ${assignment.name}.`); }
        if(late&&new Date(late)<new Date(due))throw new Error(`Late deadline precedes due date for ${assignment.name}.`);const canvasCurrentDue=existing?.due_at||assignment.due_at,canvasCurrentLate=existing?existing.lock_at:assignment.lock_at,gsCurrentDue=gsExtension?.settings?.due_date?.value||gsAssignment?.due||null,gsCurrentLate=gsExtension?gsExtension.settings?.hard_due_date?.value:(gsAssignment?.late||null),canvasAlreadyCorrect=sameDeadline(canvasCurrentDue,due)&&sameDeadline(canvasCurrentLate,late),gsAlreadyCorrect=Boolean(gsAssignment)&&sameDeadline(gsCurrentDue,due)&&sameDeadline(gsCurrentLate,gsExtension?(late||due):late);plans.push({row,assignment,student,existing,due,late,gs:gsAssignment,gsStudent,gsExtension,repair,canvasAlreadyCorrect,gsAlreadyCorrect,previousCanvas:{exists:Boolean(existing),due:existing?.due_at||null,late:existing?.lock_at||null,overrideId:existing?.id||null,studentIds:existing?.student_ids||[]},previousGradescope:{exists:Boolean(gsExtension),due:gsExtension?.settings?.due_date?.value||null,late:gsExtension?.settings?.hard_due_date?.value||null,userId:gsStudent?.id||null}});row.querySelector('.cgde-new-due').value=formatDateInput(due);row.querySelector('.cgde-new-late').value=formatDateInput(late);
      }
    } state.skipped=skipped;if(!plans.length&&skipped.length)throw new Error(`Nothing can be safely updated. Review the ${skipped.length} skipped student-assignment item(s).`);return plans;
  }
  function preflightReport(plans){const canvasWrites=plans.filter((plan)=>!plan.repair&&!plan.canvasAlreadyCorrect).length,gsWrites=plans.filter((plan)=>plan.gs&&!plan.gsAlreadyCorrect&&plan.gsStudent).length,unchanged=plans.reduce((count,plan)=>count+(!plan.repair&&plan.canvasAlreadyCorrect?1:0)+(plan.gs&&plan.gsAlreadyCorrect?1:0),0),unmatchedAssignments=new Set(plans.filter((plan)=>!plan.gs).map((plan)=>plan.assignment.name)),rosterIssues=plans.filter((plan)=>plan.gs&&!plan.gsStudent).map((plan)=>`${plan.student.name} — ${plan.assignment.name}`),issues=[];if(unmatchedAssignments.size)issues.push(`${unmatchedAssignments.size} assignment(s) have no unique Gradescope match`);if(rosterIssues.length)issues.push(`${rosterIssues.length} Gradescope roster match(es) are missing or ambiguous`);if(state.skipped.length)issues.push(`${state.skipped.length} student-assignment item(s) are skipped for safety`);return {canvasWrites,gsWrites,totalWrites:canvasWrites+gsWrites,unchanged,issues,text:[`PREFLIGHT — ${plans.length} student-assignment item(s)`,`Canvas writes: ${canvasWrites}  •  Gradescope writes: ${gsWrites}  •  Already correct: ${unchanged}`,issues.length?`Issues:\n${issues.map((issue)=>`• ${issue}`).join('\n')}`:'No blocking match or safety issues detected.'].join('\n\n')};}
  async function preview(){ try{const plans=await makePlans(),report=preflightReport(plans),lines=plans.map((p)=>{const oneStudent=selectedStudents().length===1,current=oneStudent?state.current.get(String(p.assignment.id)):null,canvasAction=p.canvasAlreadyCorrect?'Canvas already correct — skip':(p.existing?'Overwrite Canvas override':'Create Canvas override'),gsAction=!p.gs?'No Gradescope match':!p.gsStudent?'Gradescope student not uniquely matched':(p.gsAlreadyCorrect?'Gradescope already correct — skip':(oneStudent?(current?.gsExtension?'Overwrite Gradescope extension':'Create Gradescope extension'):'Create or overwrite Gradescope extension'));return `${p.student.name} — ${p.assignment.name}\n  Due: ${displayDate(p.due)}\n  Until: ${displayDate(p.late)}\n  ${p.repair?`${gsAction}; Canvas will not be changed`:`${canvasAction}; ${gsAction}`}`;}).join('\n\n'),skipped=state.skipped.length?`\n\nSkipped for safety (${state.skipped.length}):\n${state.skipped.map((item)=>`• ${item.student?item.student.name+' — ':''}${item.assignment.name} — ${item.reason}`).join('\n')}`:'';if(!report.totalWrites){setStatus('Preflight complete: all matched destinations are already correct; no writes are needed.','cgde-ok');document.getElementById('cgde-apply').disabled=true;return;}if(confirm(`${report.text}\n\nDETAILS\n\n${lines}${skipped}\n\nNothing changes until you click Apply.`)){state.plans=plans;document.getElementById('cgde-apply').disabled=false;setStatus(`Preflight confirmed: ${report.totalWrites} write(s) across ${plans.length} student-assignment item(s). Click Apply to continue.`,'cgde-ok');}else setStatus('Preflight cancelled.');}catch(e){showError(e);} }
  async function saveCanvas(plan){if((plan.existing?.student_ids||[]).length>1)throw new Error('Refusing to overwrite a Canvas override shared by multiple students.'); const body={assignment_override:{student_ids:[plan.student.id],title:`Extension — ${plan.student.name}`,due_at:plan.due,lock_at:plan.late}}; const path=plan.existing?`/api/v1/courses/${courseId}/assignments/${plan.assignment.id}/overrides/${plan.existing.id}`:`/api/v1/courses/${courseId}/assignments/${plan.assignment.id}/overrides`; return canvasRequest(path,{method:plan.existing?'PUT':'POST',body:JSON.stringify(body)}); }
  function closeEnough(first,second){return first&&second&&Math.abs(new Date(first).getTime()-new Date(second).getTime())<60000;}
  function sameDeadline(first,second){return (!first&&!second)||closeEnough(first,second);}
  async function verifyGradescopeExtension(assignmentId,userId,due,late){const page=await gsRequest('GET',`/courses/${state.gs.course.id}/assignments/${assignmentId}/extensions`),extension=extensionRows(page.responseText).find((item)=>String(item.user_id)===String(userId));if(!extension)throw new Error('Gradescope did not create an extension for this student.');const settings=extension.settings||{},actualDue=settings.due_date?.value,actualLate=settings.hard_due_date?.value,expectedLate=late||due;if(!closeEnough(actualDue,due)||!closeEnough(actualLate,expectedLate))throw new Error(`Gradescope extension verification failed: saved dates do not match the requested dates.`);return true;}
  async function saveGradescope(plan){ if(!plan.gs||!state.gs?.course)return null; const email=(plan.student.email||'').toLowerCase(), hits=state.gs.students.filter((s)=>s.email===email); if(hits.length!==1)throw new Error('student email did not uniquely match'); const settings={visible:true,due_date:{type:'absolute',value:plan.due},hard_due_date:{type:'absolute',value:plan.late||plan.due}}; await gsRequest('POST',`/courses/${state.gs.course.id}/assignments/${plan.gs.id}/extensions`,{override:{user_id:hits[0].id,settings}});return verifyGradescopeExtension(plan.gs.id,hits[0].id,plan.due,plan.late); }
  function showSummary(results){const clean=results.filter((r)=>!r.errors.length),unchanged=clean.filter((r)=>r.canvas==='unchanged'&&(r.gs==='unchanged'||r.gs===null)),both=clean.filter((r)=>r.canvas!==null&&r.gs!==null&&!unchanged.includes(r)),repaired=clean.filter((r)=>r.canvas===null&&r.gs!==null),canvasOnly=clean.filter((r)=>r.canvas!==null&&r.gs===null&&!unchanged.includes(r)),failed=results.filter((r)=>r.errors.length),skipped=state.skipped;const section=document.getElementById('cgde-summary'),list=(rows)=>`<ul>${rows.map((r)=>`<li><strong>${escapeHtml(r.name)}</strong>${r.errors.length?`<div class="cgde-summary-note">${r.errors.map(escapeHtml).join(' • ')}</div>`:''}</li>`).join('')}</ul>`;section.innerHTML=`<div class="cgde-summary-head"><h3>Deadline update summary</h3><button type="button" class="cgde-button" id="cgde-summary-close">Dismiss</button></div>${unchanged.length?`<h4 class="cgde-muted">Already correct — no write needed (${unchanged.length})</h4>${list(unchanged)}`:''}${both.length?`<h4 class="cgde-ok">Correct in Canvas and Gradescope (${both.length})</h4>${list(both)}`:''}${repaired.length?`<h4 class="cgde-ok">Gradescope correct; Canvas left unchanged (${repaired.length})</h4>${list(repaired)}`:''}${canvasOnly.length?`<h4 class="cgde-warn">Canvas correct; no unique Gradescope assignment match (${canvasOnly.length})</h4>${list(canvasOnly)}`:''}${skipped.length?`<h4 class="cgde-muted">Skipped for safety (${skipped.length})</h4><ul>${skipped.map((item)=>`<li><strong>${escapeHtml(`${item.student?item.student.name+' — ':''}${item.assignment.name}`)}</strong><div class="cgde-summary-note">${escapeHtml(item.reason)}</div></li>`).join('')}</ul>`:''}${failed.length?`<div class="cgde-summary-errors"><h4 class="cgde-error">Needs attention (${failed.length})</h4>${list(failed)}</div>`:''}`;section.classList.remove('cgde-hidden');section.querySelector('#cgde-summary-close').addEventListener('click',()=>section.classList.add('cgde-hidden'));section.scrollIntoView({behavior:'smooth',block:'nearest'});}
  async function applyPlans(){ if(!state.plans.length)return; document.getElementById('cgde-apply').disabled=true;document.getElementById('cgde-preview').disabled=true;document.getElementById('cgde-summary').classList.add('cgde-hidden');const stopButton=document.getElementById('cgde-stop');stopButton.classList.remove('cgde-hidden');stopButton.disabled=false;stopButton.textContent='Stop after current item';state.stopRequested=false; const results=[],total=state.plans.length;
    for(let index=0;index<total;index++){if(state.stopRequested)break;const plan=state.plans[index];setStatus(`Item ${index+1} of ${total}: ${plan.student.name} — ${plan.assignment.name}`);let canvas=plan.repair?null:(plan.canvasAlreadyCorrect?'unchanged':false),gs=plan.gs?(plan.gsAlreadyCorrect?'unchanged':false):null,errors=[];if(!plan.repair&&canvas!=="unchanged"){try{await saveCanvas(plan);canvas=true;}catch(e){errors.push(`Canvas: ${e.message}`);}}if(plan.gs&&gs!=="unchanged"){try{await saveGradescope(plan);gs=true;}catch(e){errors.push(`Gradescope: ${e.message}`);}}results.push({studentId:String(plan.student.id),assignmentId:String(plan.assignment.id),gradescopeId:plan.gs?.id||null,name:`${plan.student.name} — ${plan.assignment.name}`,assignmentName:plan.assignment.name,due:plan.due,late:plan.late,canvas,gs,errors,previousCanvas:plan.previousCanvas,previousGradescope:plan.previousGradescope});}
    const stopped=state.stopRequested,remaining=total-results.length;stopButton.classList.add('cgde-hidden');document.getElementById('cgde-preview').disabled=false;state.plans=[];if(results.length)writeHistory(results);state.current.clear();renderQueue();showSummary(results);setStatus(stopped?`Stopped safely after ${results.length} item(s); ${remaining} item(s) were not started.`:(results.some((r)=>r.errors.length)?'Finished with items needing attention.':'All requested updates finished.')); }

  buildUi();
})();
