export default [
  {
    files: [
      "honeycomb.js",
      "login-theme.js",
      "scripts/**/*.mjs",
      "test/**/*.mjs",
    ],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        AbortController: "readonly",
        Blob: "readonly",
        CustomEvent: "readonly",
        document: "readonly",
        fetch: "readonly",
        globalThis: "readonly",
        history: "readonly",
        Image: "readonly",
        location: "readonly",
        MutationObserver: "readonly",
        navigator: "readonly",
        Node: "readonly",
        URL: "readonly",
        window: "readonly",
        clearInterval: "readonly",
        clearTimeout: "readonly",
        console: "readonly",
        setInterval: "readonly",
        setTimeout: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        caches: "readonly",
      },
    },
    rules: {
      "no-constant-condition": "error",
      "no-debugger": "error",
      "no-dupe-keys": "error",
      "no-unreachable": "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
];
